name: medhealthplus
description: X-Ray, Ultrasound & Blood Test Online Booking System for India
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  
  # Navigation
  go_router: ^12.1.3
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.0
  
  # Local Storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Payments
  razorpay_flutter: ^1.3.6
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^10.4.5
  
  # Date & Time
  table_calendar: ^3.0.9
  
  # PDF
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
