// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcm5jKq8M7BthRXsYjTebhuYz8mh3Ipwo',
    appId: '1:153729404704:web:983b5f0fea50ac16a45145',
    messagingSenderId: '153729404704',
    projectId: 'medhealthplus-87b99',
    authDomain: 'medhealthplus-87b99.firebaseapp.com',
    storageBucket: 'medhealthplus-87b99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcm5jKq8M7BthRXsYjTebhuYz8mh3Ipwo',
    appId: '1:153729404704:android:983b5f0fea50ac16a45145',
    messagingSenderId: '153729404704',
    projectId: 'medhealthplus-87b99',
    authDomain: 'medhealthplus-87b99.firebaseapp.com',
    storageBucket: 'medhealthplus-87b99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrQPVRHk0aruz1vRFVJcToFmDIjUsztc',
    appId: '1:153729404704:ios:9a787471098041f0a45145',
    messagingSenderId: '153729404704',
    projectId: 'medhealthplus-87b99',
    authDomain: 'medhealthplus-87b99.firebaseapp.com',
    storageBucket: 'medhealthplus-87b99.firebasestorage.app',
    iosBundleId: 'com.example.medhealthplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGrQPVRHk0aruz1vRFVJcToFmDIjUsztc',
    appId: '1:153729404704:ios:9a787471098041f0a45145',
    messagingSenderId: '153729404704',
    projectId: 'medhealthplus-87b99',
    authDomain: 'medhealthplus-87b99.firebaseapp.com',
    storageBucket: 'medhealthplus-87b99.firebasestorage.app',
    iosBundleId: 'com.example.medhealthplus',
  );
}