// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6Te6KaJ2PZqDjhafUODhyBZWc6M',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'medhealthplus-demo',
    authDomain: 'medhealthplus-demo.firebaseapp.com',
    storageBucket: 'medhealthplus-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrZ-j0U_m5Nb2-TgH_Gg8',
    appId: '1:448618578101:android:aa79a932fbeeaac3efc',
    messagingSenderId: '448618578101',
    projectId: 'medhealthplus-demo',
    storageBucket: 'medhealthplus-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6Te6KaJ2PZqDjhafUODhyBZWc6M',
    appId: '1:448618578101:ios:34495e439240329cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'medhealthplus-demo',
    storageBucket: 'medhealthplus-demo.appspot.com',
    iosClientId: '448618578101-2lgvejrq9j8376694b6hvgf70j58nip2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medhealthplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7wWai6Te6KaJ2PZqDjhafUODhyBZWc6M',
    appId: '1:448618578101:ios:34495e439240329cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'medhealthplus-demo',
    storageBucket: 'medhealthplus-demo.appspot.com',
    iosClientId: '448618578101-2lgvejrq9j8376694b6hvgf70j58nip2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medhealthplus',
  );
}